version: "3.7"

services:

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener:latest
    networks:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  proxy:
    image: dockerflow/docker-flow-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm

  keycloak:
    image: jboss/keycloak
    networks:
      - proxy
      - keycloak
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=keycloakDB
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Password01
      - PROXY_ADDRESS_FORWARDING=true
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=8080
        - com.df.srcPort=80

  keycloakDB:
    image: postgres
    networks:
      - keycloak
    volumes:
      - keycloak_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password

networks:
    proxy:
    keycloak:

volumes:
    keycloak_database:
