version: "3.6"

services:

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener:latest
    networks:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  proxy:
    image: dockerflow/docker-flow-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm

  keycloak:
    image: jboss/keycloak
    networks:
      - proxy
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
    secrets:
      - keycloak-pass
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=8080
        - com.df.srcPort=80

networks:
    proxy:

secrets:
    keycloak-pass:
      file: $PWD/secrets/keycloak/pass.txt
